version: "3.5"

services:
  db:
    image: postgres:16
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senhaPostgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "100MB"

  api01: &api
    build: .
    image: giovannnavsousa04/rinha-backend:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:senhaPostgres@db:5432/rinha?sslmode=disable
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
